### ISSUE TITLE
Unsubscribe from texts

### ISSUE THREAD

**Issue by alexwileyy** [HaCSBCU/MesaHub#29]
Add online form for a person to unsubscribe from texts

**Comment by PandelisZ** [comment]
This should be flipped, to 

The attendee can register to texts. 

Let's make this an op-in feature as:

- People won't have given in their phone number
- People may not want to be opte in to this by default

**Comment by alexwileyy** [comment]
Ageeed, this should change to register mobile. I'll close issue and raise another.
