### ISSUE TITLE
AWS Architecture

### ISSUE THREAD

**Issue by alexwileyy** [HaCSBCU/MesaHub#3]
Configure AWS architecture:
- SSL Certificate
- EC2 Node Instance
- Point towards mesa.bullhacks.io

**Comment by PandelisZ** [comment]
I'm going to instead aim to make this deploy-able and testable via docker.

Also we should maybe keep mesa generic and separate form bullhacks and provide it as a service for other hackathon organisers.

something like `bullhacks.mesahub.TLD`

**Comment by alexwileyy** [comment]
@PandelisZ RE: final point, very much agree, I think this has real potential for us to provide this product as a service 👍 

Let's think of this as a service that we're independently providing to bullhacks
