### ISSUE TITLE
Text System

### ISSUE THREAD

**Issue by alexwileyy** [HaCSBCU/MesaHub#5]
System should:
- Be able to send broadcast message to all attendees.
- Send wave texts to groups.
- Message individual attendees ?

**Comment by PandelisZ** [comment]
How about browser notifications as an extension to this also.

As used at google chrome dev summit: https://www.youtube.com/watch?v=b3XFjWInBog

**Comment by alexwileyy** [comment]
@PandelisZ could you let me know a specific point in the video? But yeah sure, as long as it sticks within the scope of the design and gives us the functionality above :)

**Comment by alexwileyy** [comment]
@PandelisZ need to be completed by Thursday latest for testing.
