### ISSUE TITLE
Move DB To a SQL type db

### ISSUE THREAD

**Issue by PandelisZ** [HaCSBCU/MesaHub#50]
Move away from an object store to a standardised just normal sane DB.

**Comment by PandelisZ** [comment]
Proposal for database structure

![screen shot 2017-03-14 at 19 24 27](https://cloud.githubusercontent.com/assets/8436717/23918740/0b8c879e-08ec-11e7-89ad-2893bd532526.png)

**Comment by PandelisZ** [comment]
Added in tables for events and schedule

**Comment by alexwileyy** [comment]
@PandelisZ I would recommend reorganising this view completely. Not critiquing the design itself but it should be laid out in a more hierarchical structure with better placements of tables to make it far less confusing for new people to understand the database structure.

There appear to be several issues with it. I've outlined what I believe to be in need of looking at below: 
  - 'hackathon' table and 'hackathon_attendees' tables have two links between them. This could be represented by one singular link.
  - Should a hackathon owner be related to both announcements and events? Surly they are simply related to a hackathon on which they can make changes?
  - If a hackathon owner is connected to both events:
    - There is a foreign key missing on Hackathon events from the user owner 
    - The foreign key is not properly identified on the hackathon_announements table
  - What is the connection between the user__attendee and the hackathon_attendee, and what is the need for a more than sign on the hackathon_attendee table?

Just wanted to make sure that we have the database design solid before we go about changing things on such a massive scale.

**Comment by alexwileyy** [comment]
@PandelisZ I forgot to mention, good work overall, I just wanna bring these concerns so that we can flesh out any potential issues now rather than in development <3

**Comment by PandelisZ** [comment]
The thinking behind the usr_attendee & hackathon_Attendee table is that a hacker can choose to go to more than one hackathon. So why register them twice. 

The hackathon_ateendee table exists to solve the many to many relation that would occur in the situation that a hacker wants to attend multiple hackathons with a single account.

The hackathon_attendee table is what we're interested from a hackathon, and the usr_attendee table is the users actual account.

On the events front. I thought it would be good jsut to attach a created_by field, ie: ownerid to anything created so that people can keep track of who made what. And yes we could add that to pages sure. However, pages are a bit more generalised but yeah sure we can do no harm done.

not sure what you mean by point one with the singular link though.

the foreign key issue, yeah missed that i'll add them in

**Comment by alexwileyy** [comment]
@PandelisZ 

Okay, thank you for clearing those points up, knowing of the purpose of the two user tables clears a lot of it up for me. I think as a general principle, anything that a hackathon owner can create should be given an owner ID so we can keep track of exactly what has been modified in event.

I would like you to also add an additional logs table. This is where I would like to collate logs ordered by time of what goes on across all hackathons. It will draw data such as:
  - When an organiser sends a text
  - When an announcement is sent
  - Events added
  - Etc etc
For every row in this table there will be an associated user id. Sound good?

Hackathon and Hackathon_announcements have two links between them, as in two physical lines on the drawing. It could be represented by one?

I would still recommend just organising it and trying to mitigate as many lines crossing over as possible for when new devs come onto the project.

Sweet, good job mate

**Comment by PandelisZ** [comment]
One of those links is going to hackathon_schedule

**Comment by PandelisZ** [comment]
#61 nearly closed this, still need the login type stuff

**Comment by PandelisZ** [comment]
Some added features here: http://docs.sequelizejs.com/en/latest/

**Comment by PandelisZ** [comment]
LOL we put a lot of work in to this
