### ISSUE TITLE
'docker-compose up' doesn't work.

### ISSUE THREAD

**Issue by luketainton** [HaCSBCU/MesaHub#69]
### See log below.

Attaching to mesahub_mongodata_1, mesahub_web_1, mesahub_mongo_1
[36mmesahub_mongodata_1 exited with code 0
[0m[32mmongo_1      |[0m 2018-01-17T17:12:04.157+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=9bb3db601e25
[32mmongo_1      |[0m 2018-01-17T17:12:04.157+0000 I CONTROL  [initandlisten] db version v3.6.2
[32mmongo_1      |[0m 2018-01-17T17:12:04.157+0000 I CONTROL  [initandlisten] git version: 489d177dbd0f0420a8ca04d39fd78d0a2c539420
[32mmongo_1      |[0m 2018-01-17T17:12:04.157+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
[32mmongo_1      |[0m 2018-01-17T17:12:04.157+0000 I CONTROL  [initandlisten] allocator: tcmalloc
[32mmongo_1      |[0m 2018-01-17T17:12:04.157+0000 I CONTROL  [initandlisten] modules: none
[32mmongo_1      |[0m 2018-01-17T17:12:04.157+0000 I CONTROL  [initandlisten] build environment:
[32mmongo_1      |[0m 2018-01-17T17:12:04.157+0000 I CONTROL  [initandlisten]     distmod: debian81
[32mmongo_1      |[0m 2018-01-17T17:12:04.157+0000 I CONTROL  [initandlisten]     distarch: x86_64
[32mmongo_1      |[0m 2018-01-17T17:12:04.157+0000 I CONTROL  [initandlisten]     target_arch: x86_64
[32mmongo_1      |[0m 2018-01-17T17:12:04.157+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } }
[32mmongo_1      |[0m 2018-01-17T17:12:04.158+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
[32mmongo_1      |[0m 2018-01-17T17:12:04.158+0000 I STORAGE  [initandlisten] 
[32mmongo_1      |[0m 2018-01-17T17:12:04.158+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
[32mmongo_1      |[0m 2018-01-17T17:12:04.158+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
[32mmongo_1      |[0m 2018-01-17T17:12:04.158+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3403M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
[32mmongo_1      |[0m 2018-01-17T17:12:04.290+0000 I STORAGE  [initandlisten] WiredTiger message [1516209124:290317][1:0x7f22b994fa00], txn-recover: Main recovery loop: starting at 6/4736
[33mweb_1        |[0m 
[33mweb_1        |[0m > mesahub@0.2.0 start /app
[33mweb_1        |[0m > node ./bin/www
[33mweb_1        |[0m 
[33mweb_1        |[0m module.js:471
[33mweb_1        |[0m     throw err;
[33mweb_1        |[0m     ^
[33mweb_1        |[0m 
[33mweb_1        |[0m Error: Cannot find module 'express'
[33mweb_1        |[0m     at Function.Module._resolveFilename (module.js:469:15)
[33mweb_1        |[0m     at Function.Module._load (module.js:417:25)
[33mweb_1        |[0m     at Module.require (module.js:497:17)
[33mweb_1        |[0m     at require (internal/module.js:20:19)
[33mweb_1        |[0m     at Object.<anonymous> (/app/main.js:1:77)
[33mweb_1        |[0m     at Module._compile (module.js:570:32)
[33mweb_1        |[0m     at Object.Module._extensions..js (module.js:579:10)
[33mweb_1        |[0m     at Module.load (module.js:487:32)
[33mweb_1        |[0m     at tryModuleLoad (module.js:446:12)
[33mweb_1        |[0m     at Function.Module._load (module.js:438:3)
[33mweb_1        |[0m 
[33mweb_1        |[0m npm ERR! Linux 4.13.0-25-generic
[33mweb_1        |[0m npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
[33mweb_1        |[0m npm ERR! node v6.12.3
[33mweb_1        |[0m npm ERR! npm  v3.10.10
[33mweb_1        |[0m npm ERR! code ELIFECYCLE
[33mweb_1        |[0m npm ERR! mesahub@0.2.0 start: `node ./bin/www`
[33mweb_1        |[0m npm ERR! Exit status 1
[33mweb_1        |[0m npm ERR! 
[33mweb_1        |[0m npm ERR! Failed at the mesahub@0.2.0 start script 'node ./bin/www'.
[33mweb_1        |[0m npm ERR! Make sure you have the latest version of node.js and npm installed.
[33mweb_1        |[0m npm ERR! If you do, this is most likely a problem with the mesahub package,
[33mweb_1        |[0m npm ERR! not with npm itself.
[33mweb_1        |[0m npm ERR! Tell the author that this fails on your system:
[33mweb_1        |[0m npm ERR!     node ./bin/www
[33mweb_1        |[0m npm ERR! You can get information on how to open an issue for this project with:
[33mweb_1        |[0m npm ERR!     npm bugs mesahub
[33mweb_1        |[0m npm ERR! Or if that isn't available, you can get their info via:
[33mweb_1        |[0m npm ERR!     npm owner ls mesahub
[33mweb_1        |[0m npm ERR! There is likely additional logging output above.
[33mweb_1        |[0m npm WARN Local package.json exists, but node_modules missing, did you mean to install?
[33mweb_1        |[0m 
[33mweb_1        |[0m npm ERR! Please include the following file with any support request:
[33mweb_1        |[0m npm ERR!     /app/npm-debug.log
[32mmongo_1      |[0m 2018-01-17T17:12:04.387+0000 I STORAGE  [initandlisten] WiredTiger message [1516209124:387856][1:0x7f22b994fa00], txn-recover: Recovering log 6 through 7
[32mmongo_1      |[0m 2018-01-17T17:12:04.442+0000 I STORAGE  [initandlisten] WiredTiger message [1516209124:442863][1:0x7f22b994fa00], txn-recover: Recovering log 7 through 7
[32mmongo_1      |[0m 2018-01-17T17:12:04.532+0000 I CONTROL  [initandlisten] 
[32mmongo_1      |[0m 2018-01-17T17:12:04.532+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
[32mmongo_1      |[0m 2018-01-17T17:12:04.532+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
[32mmongo_1      |[0m 2018-01-17T17:12:04.532+0000 I CONTROL  [initandlisten] 
[32mmongo_1      |[0m 2018-01-17T17:12:04.548+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
[32mmongo_1      |[0m 2018-01-17T17:12:04.549+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
[33mmesahub_web_1 exited with code 1
[0m

**Comment by PandelisZ** [comment]
Need to do npm install before launching

**Comment by PandelisZ** [comment]
Ah okay i remember there being an issue with the binary versions of npm modules. Would have to change this to build the node modules in the docker :/ HMMMMMm

**Comment by PandelisZ** [comment]
It works fine for me if i comment out the twilio line btw:

from texting.js
// const client = require('twilio')(accountSid, authToken);

**Comment by luketainton** [comment]
I'll try it later
________________________________

**Comment by PandelisZ** [comment]
Ok theres a number of issues with running the docker. Cause its expecting to read from some postgresql data.

We need to have a discord chat about it. Tomorrow?

**Comment by luketainton** [comment]
Sure, any time after 3:30pm is good 😊


Kind Regards,

Luke



[1478091948459_BCU]

Luke Tainton

Luke.Tainton@mail.bcu.ac.uk

Second Year Student, BSc(Hons) Computer Networks

School Representative for the School of Computing and Digital Technology

Faculty of Computing, Engineering and the Built Environment


[1478092071554_linkedinbutton.jpg]

https://www.linkedin.com/in/luketainton

________________________________

**Comment by seenaomi** [comment]
So is this still an issue then? I am interested in checking this project out.

**Comment by PandelisZ** [comment]
Hi @seenaomi,

There was a big change in the way we architected the project, we went from mongo to postgresql and the docker enviroment never switched over.

You can run it outside of docker if you have a postgresql server you can point it to. It could definately use some work to make the process easier to setup but we never had the time to put into doing that.

**Comment by PandelisZ** [comment]
Ok so i've actually finally fixed this in #72
